"""empty message

Revision ID: a914d6c9c36e
Revises: 1b537c697d8f
Create Date: 2024-02-24 12:56:00.730970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a914d6c9c36e'
down_revision: Union[str, None] = '1b537c697d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_words')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_words',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_guessed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_words_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_words_pkey')
    )
    # ### end Alembic commands ###
