"""empty message

Revision ID: 94a4596add96
Revises: 39d072341e49
Create Date: 2024-02-29 11:09:16.475377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a4596add96'
down_revision: Union[str, None] = '39d072341e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('today_word', sa.String(), nullable=True))
    op.drop_column('user_words', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('day', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user_words', 'today_word')
    # ### end Alembic commands ###
